apiVersion: apps/v1
kind: Deployment
metadata:
  name: application # change name as required
spec:
  replicas: 2  # Adjust based on your requirements
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: evaluation # change name as demand
        image: 771672242837.dkr.ecr.us-east-1.amazonaws.com/cap-2:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
