apiVersion: apps/v1
kind: Deployment
metadata:
  name: application # change name as demand
spec:
  replicas: 2  # Adjust based on your requirements
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: evaluation # change name as demand
        image: dsahu87/evaluation:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
