apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Use NodePort to make the service accessible externally

