apiVersion: v1
kind: Service
metadata:
  name: your-website-service
spec:
  selector:
    app: your-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Use NodePort to make the service accessible externally
